global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: stoloto-core
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['stoloto-core:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: bonus-game-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['bonus-game-service:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
