global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: core
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['core:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: service-game-lucky-rabbit
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['service-game-lucky-rabbit:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
